### ISSUE TITLE
NoClassDefFoundError: it/unimi/dsi/fastutil/ints/IntArraySet

### ISSUE THREAD

**Issue by vorburger** [LanternPowered/LanternServer#51]
I've just locally built and wanted to try this out (for the first time), but FYI upon connecting hit this:

```
➜  LanternServer git:(master) java -jar build/libs/lanternserver-1.0.0-SNAPSHOT-fat.jar
[03:05:54] [main/INFO]: Instantiated the Injector in production mode.
[03:05:54] [main/INFO]: Starting Lantern Server 1.0.0-SNAPSHOT
[03:05:54] [main/INFO]:    for  Minecraft 1.12.2 with protocol version 340
[03:05:54] [main/INFO]:    with SpongeAPI 7.0.0-SNAPSHOT
[03:05:54] [main/INFO]: Searching for plugins...
[03:05:54] [main/INFO]: 0 plugin(s) found
[03:05:56] [main/INFO]: Epoll is enabled.
[03:05:57] [main/INFO]: Successfully bound to: /0:0:0:0:0:0:0:0%0:25565
[03:05:57] [main/INFO]: Ready for connections.
[03:05:57] [main/INFO] [world/Overworld]: Generating spawn volume...
[03:05:57] [main/INFO] [world/Overworld]: Finished generating spawn volume.
[03:06:42] [async-0/INFO]: Finished authenticating.
[03:06:42] [server/INFO]: michaelpapa7: Skip forge handshake.
[03:06:43] [server/ERROR]: Error while handling org.lanternpowered.server.network.forge.message.type.handshake.MessageForgeHandshakeInStart@11f10d58
java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/ints/IntArraySet
	at org.lanternpowered.server.inventory.client.ClientContainer.<init>(ClientContainer.java:364) ~[?:1.0.0-SNAPSHOT]
	at org.lanternpowered.server.inventory.client.PlayerClientContainer.<init>(PlayerClientContainer.java:61) ~[?:1.0.0-SNAPSHOT]
	at org.lanternpowered.server.inventory.PlayerInventoryContainer.<init>(PlayerInventoryContainer.java:49) ~[?:1.0.0-SNAPSHOT]
	at org.lanternpowered.server.entity.living.player.LanternPlayer.<init>(LanternPlayer.java:260) ~[?:1.0.0-SNAPSHOT]
	at org.lanternpowered.server.network.NetworkSession.initPlayer(NetworkSession.java:819) ~[?:1.0.0-SNAPSHOT]
	at org.lanternpowered.server.network.forge.message.handler.handshake.HandlerForgeHandshakeInStart.handle(HandlerForgeHandshakeInStart.java:80) ~[?:1.0.0-SNAPSHOT]
	at org.lanternpowered.server.network.forge.message.handler.handshake.HandlerForgeHandshakeInStart.handle(HandlerForgeHandshakeInStart.java:47) ~[?:1.0.0-SNAPSHOT]
	at org.lanternpowered.server.network.NetworkSession.handleMessage(NetworkSession.java:254) ~[?:1.0.0-SNAPSHOT]
	at org.lanternpowered.server.network.NetworkSession.pulse(NetworkSession.java:461) ~[?:1.0.0-SNAPSHOT]
	at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4649) ~[?:1.8.0_151]
	at java.util.Collections$SetFromMap.forEach(Collections.java:5476) ~[?:1.8.0_151]
	at org.lanternpowered.server.network.NetworkManager.pulseSessions(NetworkManager.java:100) ~[?:1.0.0-SNAPSHOT]
	at org.lanternpowered.server.LanternServer.pulse(LanternServer.java:370) ~[?:1.0.0-SNAPSHOT]
	at org.lanternpowered.server.LanternServer.lambda$start$2(LanternServer.java:290) ~[?:1.0.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.ClassNotFoundException: it.unimi.dsi.fastutil.ints.IntArraySet
	at org.lanternpowered.launch.LanternClassLoader.findClass(LanternClassLoader.java:486) ~[lanternserver-1.0.0-SNAPSHOT-fat.jar:1.0.0-SNAPSHOT]
	at org.lanternpowered.launch.LanternClassLoader.loadClass(LanternClassLoader.java:447) ~[lanternserver-1.0.0-SNAPSHOT-fat.jar:1.0.0-SNAPSHOT]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
	... 21 more
> 
```

I loved how much faster than Sponge Vanilla it appears to start up... now if only it actually worked! :smile:

**Comment by Cybermaxke** [comment]
Yet another fastutil class I forgot to shade, I will take a look at it later. This issue won't be able to occur once the `jitpack` branch (no longer related to jitpack) gets merged.
